### ISSUE TITLE
Radius units

### ISSUE THREAD

**Issue by jonnymaserati** [pro-well-plan/torque_drag#1]
I think you're mixing units here?
https://github.com/pro-well-plan/torque_drag/blob/6fcf3587aa0df3d84a4f3a37f64ef3f8547a7a38/torque_drag/main.py#L150
In the example in the documents, it appears that the diameters are input in inches but I don't see a conversion to metric in the code where the forces are being calculated in metric?

**Comment by jcamiloangarita** [comment]
You're right @jonnymaserati, thanks 🙂. _torque_drag_ was living inside the package _pwptemp_, so it was using inputs from there such as .r1, .r2 and .r3 and the units conversions were running there. The inputs are now rearranged and unit conversion added, a new version will be released (**v0.0.8**) to cover these changes.
