### ISSUE TITLE
KeyError for 'pipe'

### ISSUE THREAD

**Issue by ndenzin** [pro-well-plan/torque_drag#4]
I copied and pasted the example code from the documentation section to see what this would look like.  Unfortunately, I am having issues, which are probably on my end, as I am new to programming.  I received a KeyError for 'pipe'.  Reading the traceback log, and looking back at the source code, I am not sure what the issue is.  I do have a trajectory in the library, that did plot fine using your other well_profile script. Any help on this, or suggestions would be great.  Thanks!

![image](https://user-images.githubusercontent.com/78862706/127230553-84c317e0-172c-482e-9bcd-cacedaf07ed5.png)
Apologies, I tried to insert the code exactly as written, but showed up messy on the preview, so I just used a screen shot instead.

**Comment by jcamiloangarita** [comment]
New version was just released with some tweaks, and [documentation](https://torque-drag.readthedocs.io/en/latest/calculations.html) is now updated with the latest structure.
